### ISSUE TITLE
Errors in 1.8.2

### ISSUE THREAD

**Issue by edcafenet** [mitmedialab/UrbanSwarms#3]
When you load the this model into Gama 1.8.2, there are a couple of errors that prevent running the experiments:

-  Line 399 -> No operator found for applying 'internal_at' to types [unknown, list] (operators available for [types [container, list], types [geometry, list], types [agent, list]])
- Line 400 -> No operator found for applying 'internal_at' to types [container, list] (operators available for [types [container, list], types [geometry, list], types [agent, list]])
- Line 425 -> No operator found for applying 'internal_at' to types [container, list] (operators available for [types [container, list], types [geometry, list], types [agent, list]])

**Comment by agrignard** [comment]
Which model (.gaml) are you refering too?

**Comment by edcafenet** [comment]
UrbanSwarm_main.gaml

**Comment by agrignard** [comment]
It's now compiling but there is error at run time 

````
 at cycle 0: Java error: wrong casting
ClassCastException: java.lang.Double incompatible with java.lang.Integer
java.base/java.lang.Integer.compareTo(Integer.java:64)
msi.gama.kernel.experiment.ExperimentParameter.setAndVerifyValue(ExperimentParameter.java:351)
msi.gama.kernel.experiment.ExperimentParameter.setValue(ExperimentParameter.java:429)
msi.gama.kernel.experiment.ExperimentParameter.tryToInit(ExperimentParameter.java:439)
msi.gama.kernel.experiment.ExperimentParameter.getValue(ExperimentParameter.java:688)
msi.gama.kernel.experiment.ExperimentParameter.value(ExperimentParameter.java:590)
ummisco.gama.ui.parameters.AbstractEditor.retrieveValueOfParameter(AbstractEditor.java:223)
Impossible to obtain the value of PheromoneMarkIntensity
````

**Comment by agrignard** [comment]
Runtime is ok now but the simulation goes weird

`````
2 occurrences in 2 agents at cycle 1: Can not execute ask on a nil agent
in ask closest_to(closeTag,self)  {
	loop j from: 0 to: length(self.pheromonesToward) - 1  {
		self.pheromones[j] <- (self.pheromones[j] + myself.pheromoneToDiffuse) - ((singlePheromoneMark * evaporation) * (cycle - self.lastUpdate));
		if self.pheromones[j] < 0.001  {
			self.pheromones[j] <- 0;
		}
	
		if myself.carrying  {
			if self.pheromonesToward[j] = myself.source  {
				self.pheromones[j] <- self.pheromones[j] + myself.pheromoneMark;
			}
		
		}
`````

**Comment by edcafenet** [comment]
I tried to run the code and my Mac goes crazy. I need to restart it in order to make useful again :/

**Comment by agrignard** [comment]
do you have the same runtime error?

**Comment by edcafenet** [comment]
After 10 secs of running the simulation yes!

**Comment by agrignard** [comment]
We should be all set the model is rerunning as it was in 1.8.1. The syntax has been updated to run with 1.8.2

Concerning the runtime nothing has changed in the code since 2018 and 1.8.2 should be in theory faster than 1.8.1. Let me know if you still have issue on your personal computer and if yes can you share your configuration (OS, GPU, etc)

**Comment by edcafenet** [comment]
Thanks dude!
